引入最新的微信sdk，添加分享小程序，打开小程序功能
yorkie/react-native-wechat pull request #381
Opened 2018-08-25 12:24 UTC by puti94

引入了最新的1.8.2的微信sdk，添加了分享小程序以及打开小程序的桥接方法，以及更新android最新isWXAppSupportApi方法，望采纳

2018-08-27 08:12 UTC, puti94 commented
问题修改了

2018-08-29 02:43 UTC, ganlanshu0211 commented
正好需要，关注中

2018-09-04 01:58 UTC, allenxieyusheng commented
这个问题解决了嘛？？？有API的实例不

2018-09-04 02:06 UTC, puti94 commented
@allenxieyusheng  https://github.com/puti94/react-native-wechat  可以试下，API进入源码看注释就好

2018-09-05 10:18 UTC, songxiaoliang commented
@puti94 调用哪个方法实现分享小程序卡片到微信好友呢？期待您到回复

2018-09-05 10:37 UTC, songxiaoliang commented
@puti64 需要更新sdk吗兄弟

2018-09-06 04:04 UTC, allenxieyusheng commented
@puti94 你这个截图是哪里来的？是哪个文件？我跟新了一下到v1.9.10;在源码里index.js没看到关于小程序的注释

2018-09-10 07:56 UTC, allenxieyusheng commented
@puti94 安卓调试无效参数是什么鬼？

2018-09-17 12:37 UTC, ganlanshu0211 commented
@puti94 非常感谢这个PR，我现在可以跳转小程序了。但是我发现用了这个PR之后，安卓版微信支付无法跳转了，WeChat API invoke returns false。我用回原版的微信支付就可以跳转

2018-09-17 13:05 UTC, puti94 commented
@ganlanshu0211   刚提交了一些东西，你可以试下，因为之前不是用最新的react-native-wechat 版本改的，没注意支付问题

2018-09-17 14:10 UTC, ganlanshu0211 commented
@puti94 好的，多谢大神


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

2018-10-11 20:44 UTC, yorkie requested changes
有几处需要修改。

2018-10-11 20:44 UTC, yorkie commented on package.json
> +  "version": "1.9.10",
多谢，这里需要修改为 1.10.0

2018-10-11 20:44 UTC, yorkie commented on ios/RCTWeChat.m
> +    }else if ([resp isKindOfClass:[WXLaunchMiniProgramResp class]])
这里的格式需要改一下。

2018-10-11 20:44 UTC, yorkie commented on index.js
> -  }
文件缩进有问题。

2018-10-11 20:44 UTC, yorkie commented on index.js
>      });
同上。

2018-10-12 12:06 UTC, closed without merging

2019-07-25 03:34 UTC, xxj95719 commented
这个pr合并了吗？我装的1.9.10  index.js中没有发现打开小程序的方法

2019-12-15 03:39 UTC, snail714 commented
现在可以拉起小程序了吗？