fix interface ShareMetadata
yorkie/react-native-wechat pull request #527
Opened 2019-10-14 06:19 UTC by Jhaidi

修复ShareMetaddata这个interface

不添加title时，用户调用wechat.shareToTimeline或者wechat.shareToSession进行分享时，会没有标题，导致对话列表出现[链接]null的情况

2019-10-14 06:31 UTC, yorkie commented
title 是否需要必填呢？会有没有标题分享的情况吗？

2019-10-14 07:26 UTC, Jhaidi commented
当分享链接类型为news时，不管是发送给好友还是分享到朋友圈都需要title才能正常显示，但是当分享的类型为你text时则不需要title字段，所以我个人觉得不需要必传，但如果项目中的sharemetadata能够按照分享类型做具体区分的话，那样可能会更合理一些


原始邮件
发件人:Yorkie Liunotifications@github.com
收件人:yorkie/react-native-wechatreact-native-wechat@noreply.github.com
抄送:jhaidihaidi_jin@163.com; Authorauthor@noreply.github.com
发送时间:2019年10月14日(周一) 14:31
主题:Re: [yorkie/react-native-wechat] fix interface ShareMetadata (#527)


title 是否需要必填呢？会有没有标题分享的情况吗？
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2019-10-14 07:56 UTC, yorkie commented
> > title 是否需要必填呢？会有没有标题分享的情况吗？
> > 我又阅读了一下微信分享的[开发文档](https://developers.weixin.qq.com/doc/oplatform/Mobile_App/Share_and_Favorites/Android.html)
> 
> 只有当分享类型为音乐、视频、网页、小程序时可添加titile描述字段，但是titile都不作为必传字段做处理

好的，那这个 PR 我们先当作 Optional Property 来吧，可以在 #526 进行区分。

2019-10-14 07:56 UTC, yorkie approved these changes
LGTM

2019-10-14 07:57 UTC, yorkie commented
@M1seRy 你也看看这个 PR 是否有问题，没有问题你来合并吧 :p

2019-10-14 09:41 UTC, M1seRy commented
> @M1seRy 你也看看这个 PR 是否有问题，没有问题你来合并吧 :p

OK ，：) 晚一点我有时间 。

2019-10-15 02:45 UTC, 0xinhua requested changes
注意 interface 的写法，title?: string, => title?: string;

2019-10-15 03:15 UTC, Jhaidi commented
> 注意 interface 的写法，title?: string, => title?: string;

ok 我已经做了修改

2019-10-15 14:55 UTC, 0xinhua approved these changes
@yorkie  测试了，这个改动在 SDK 1.7.2 版本分享好友、朋友圈没有什么问题。

2019-10-15 15:11 UTC, M1seRy commented
> @M1seRy 你也看看这个 PR 是否有问题，没有问题你来合并吧 :p

好像没有 Merge PR 的权限。: )

2019-10-15 18:33 UTC, yorkie commented
https://github.com/yorkie/react-native-wechat/invitations 之前已经邀请你了，你需要在这个链接接受一下。

2019-10-16 02:23 UTC, merged

2019-10-16 02:25 UTC, M1seRy commented
@Jhaidi Thanks : )